package net.potato_modding.potatospells.screen;

public class IVCalculator {
/*
    private static double attackIV(double x){
        return (x + 1);
    }

    @SubscribeEvent(priority = net.neoforged.bus.api.EventPriority.LOWEST)
    private static void handleResistanceAttribute(EntityJoinLevelEvent event) {
        var entity = event.getEntity();
        if (!(entity instanceof LivingEntity mob)) return;

        double SpellPowerIV = 0;
        double CastReductionIV = 0;
        double ResistIV = 0;
        double FireResIV = 0;
        double IceResIV = 0;
        double HolyResIV = 0;
        double NatResIV = 0;
        double EvokeResIV = 0;
        double BloodResIV = 0;
        double EndResIV = 0;
        double LigResIV = 0;
        double EldResIV = 0;
        double AbyssResIV = 0;
        double TechResIV = 0;
        double BladeResIV = 0;
        double MindResIV = 0;
        double SoundResIV = 0;
        double WindResIV = 0;
        double SymResIV = 0;
        double SpiritResIV = 0;
        double DuneResIV = 0;
        double AquaResIV = 0;
        double ArmorPierceIV = 0;
        double ArmorShredIV = 0;
        double ProtPierceIV = 0;
        double ProtShredIV = 0;
        double CritDmgIV = 0;
        double CritIV = 0;

        if (mob.getType().is(PotatoTags.RACE_UNDEAD)) {
            SpellPowerIV = 1.2 + randMax;
            CastReductionIV = 0.9 + randMax;
            ResistIV = 1.15 + randMax;
            FireResIV = 0.85 + randMax;
            IceResIV = 1.15 + randMax;
            HolyResIV = 0.85 + randMax;
            NatResIV = 0.85 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 1.15 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 1.15 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1.15 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 0.85 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 0.85 + randMax;
            SpiritResIV = 1.15 + randMax;
            DuneResIV = 1 + randMax;
            AquaResIV = 1 + randMax;
            ArmorPierceIV = 2 + randMax;
            ArmorShredIV = 0.15 + randMax;
            ProtPierceIV = 2 + randMax;
            ProtShredIV = 0.1 + randMax;
            CritDmgIV = 1.35 + randMax;
            CritIV = 0.15 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_HUMAN)) {
            SpellPowerIV = 1.15 + randMax;
            CastReductionIV = 1.15 + randMax;
            ResistIV = 1.2 + randMax;
            FireResIV = 1 + randMax;
            IceResIV = 0.85 + randMax;
            HolyResIV = 1.15 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1 + randMax;
            BloodResIV = 0.85 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 0.85 + randMax;
            AbyssResIV = 0.85 + randMax;
            TechResIV = 1.15 + randMax;
            BladeResIV = 0.85 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 1.15 + randMax;
            WindResIV = 1 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 0.85 + randMax;
            DuneResIV = 1.15 + randMax;
            AquaResIV = 1.15 + randMax;
            ArmorPierceIV = 3 + randMax;
            ArmorShredIV = 0.2 + randMax;
            ProtPierceIV = 1.5 + randMax;
            ProtShredIV = 0.1 + randMax;
            CritDmgIV = 1.5 + randMax;
            CritIV = 0.2 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_BRUTE)) {
            SpellPowerIV = 1 + randMax;
            CastReductionIV = 0.9 + randMax;
            ResistIV = 1.2 + randMax;
            FireResIV = 1 + randMax;
            IceResIV = 0.85 + randMax;
            HolyResIV = 1 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1 + randMax;
            BloodResIV = 0.85 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 1 + randMax;
            AbyssResIV = 0.85 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 1.15 + randMax;
            MindResIV = 1 + randMax;
            SoundResIV = 1 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1 + randMax;
            DuneResIV = 1.15 + randMax;
            AquaResIV = 1.15 + randMax;
            ArmorPierceIV = 5 + randMax;
            ArmorShredIV = 0.1 + randMax;
            ProtPierceIV = 1 + randMax;
            ProtShredIV = 1.5 + randMax;
            CritDmgIV = 1.4 + randMax;
            CritIV = 0.25 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_INSECT)) {
            SpellPowerIV = 0.9 + randMax;
            CastReductionIV = 1 + randMax;
            ResistIV = 1 + randMax;
            FireResIV = 0.85 + randMax;
            IceResIV = 0.85 + randMax;
            HolyResIV = 1 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1 + randMax;
            BloodResIV = 1 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 1 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1.15 + randMax;
            TechResIV = 1.15 + randMax;
            BladeResIV = 1 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 1 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1 + randMax;
            DuneResIV = 1.15 + randMax;
            AquaResIV = 0.85 + randMax;
            ArmorPierceIV = 1 + randMax;
            ArmorShredIV = 0.25 + randMax;
            ProtPierceIV = 1 + randMax;
            ProtShredIV = 0.15 + randMax;
            CritDmgIV = 1.4 + randMax;
            CritIV = 0.25 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_FLYING)) {
            SpellPowerIV = 0.95 + randMax;
            CastReductionIV = 1.25 + randMax;
            ResistIV = 0.9 + randMax;
            FireResIV = 1 + randMax;
            IceResIV = 0.85 + randMax;
            HolyResIV = 1 + randMax;
            NatResIV = 1 + randMax;
            EvokeResIV = 1 + randMax;
            BloodResIV = -0.1 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 1 + randMax;
            AbyssResIV = 1 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 1.15 + randMax;
            MindResIV = 1 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1 + randMax;
            DuneResIV = 1 + randMax;
            AquaResIV = 0.85 + randMax;
            ArmorPierceIV = 1 + randMax;
            ArmorShredIV = 0.1 + randMax;
            ProtPierceIV = 1 + randMax;
            ProtShredIV = 0.1 + randMax;
            CritDmgIV = 1.35 + randMax;
            CritIV = 0.4 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_GOLEM)) {
            SpellPowerIV = 1.15 + randMax;
            CastReductionIV = 0.8 + randMax;
            ResistIV = 1.3 + randMax;
            FireResIV = 1.15 + randMax;
            IceResIV = 1.15 + randMax;
            HolyResIV = 0.85 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 1.15 + randMax;
            EndResIV = 0.85 + randMax;
            LigResIV = 1.15 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1.15 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 1.15 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 0.85 + randMax;
            SpiritResIV = 1.15 + randMax;
            DuneResIV = 0.85 + randMax;
            AquaResIV = 1 + randMax;
            ArmorPierceIV = 3 + randMax;
            ArmorShredIV = 0.15 + randMax;
            ProtPierceIV = 1 + randMax;
            ProtShredIV = 0.15 + randMax;
            CritDmgIV = 1.6 + randMax;
            CritIV = 0.1 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_CONSTRUCT)) {
            SpellPowerIV = 0.8 + randMax;
            CastReductionIV = 1.5 + randMax;
            ResistIV = 1.25 + randMax;
            FireResIV = 1.15 + randMax;
            IceResIV = 1.15 + randMax;
            HolyResIV = 1 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 1.15 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1 + randMax;
            TechResIV = 1.15 + randMax;
            BladeResIV = 1 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 1 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1.15 + randMax;
            DuneResIV = 0.85 + randMax;
            AquaResIV = 0.85 + randMax;
            ArmorPierceIV = 2 + randMax;
            ArmorShredIV = 0.2 + randMax;
            ProtPierceIV = 2 + randMax;
            ProtShredIV = 0.2 + randMax;
            CritDmgIV = 1.25 + randMax;
            CritIV = 1 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_FISH)) {
            SpellPowerIV = 0.95 + randMax;
            CastReductionIV = 1.2 + randMax;
            ResistIV = 0.9 + randMax;
            FireResIV = 1.15 + randMax;
            IceResIV = 1.15 + randMax;
            HolyResIV = 1 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 0.85 + randMax;
            BloodResIV = 0.85 + randMax;
            EndResIV = 1 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 1 + randMax;
            AbyssResIV = 1.15 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 0.85 + randMax;
            MindResIV = 1 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1 + randMax;
            DuneResIV = 0.85 + randMax;
            AquaResIV = 1.15 + randMax;
            ArmorPierceIV = 1.5 + randMax;
            ArmorShredIV = 0.15 + randMax;
            ProtPierceIV = 1.5 + randMax;
            ProtShredIV = 0.15 + randMax;
            CritDmgIV = 1.45 + randMax;
            CritIV = 0.15 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_SPIRIT)) {
            SpellPowerIV = 1.25 + randMax;
            CastReductionIV = 1.25 + randMax;
            ResistIV = 1.15 + randMax;
            FireResIV = 1 + randMax;
            IceResIV = 1 + randMax;
            HolyResIV = 0.85 + randMax;
            NatResIV = 1 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 0.85 + randMax;
            EndResIV = 0.85 + randMax;
            LigResIV = 1 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 1.15 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 1 + randMax;
            WindResIV = 1 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 0.85 + randMax;
            DuneResIV = 1 + randMax;
            AquaResIV = 1 + randMax;
            ArmorPierceIV = 3 + randMax;
            ArmorShredIV = 0.25 + randMax;
            ProtPierceIV = 3 + randMax;
            ProtShredIV = 0.25 + randMax;
            CritDmgIV = 1.155 + randMax;
            CritIV = 0.1 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_AMORPH)) {
            SpellPowerIV = 1.05 + randMax;
            CastReductionIV = 1.05 + randMax;
            ResistIV = 1 + randMax;
            FireResIV = 1 + randMax;
            IceResIV = 1 + randMax;
            HolyResIV = 0.85 + randMax;
            NatResIV = 0.85 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 1.15 + randMax;
            EndResIV = 1.15 + randMax;
            LigResIV = 1.15 + randMax;
            EldResIV = 1.15 + randMax;
            AbyssResIV = 1.15 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 0.85 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1 + randMax;
            SymResIV = 1 + randMax;
            SpiritResIV = 1.15 + randMax;
            DuneResIV = 1 + randMax;
            AquaResIV = 1 + randMax;
            ArmorPierceIV = 1 + randMax;
            ArmorShredIV = 0.1 + randMax;
            ProtPierceIV = 2 + randMax;
            ProtShredIV = 0.15 + randMax;
            CritDmgIV = 1.55 + randMax;
            CritIV = 0.2 + randMax;
        }
        if (mob.getType().is(PotatoTags.RACE_DRAGON)) {
            SpellPowerIV = 1.3 + randMax;
            CastReductionIV = 1.2 + randMax;
            ResistIV = 1.5 + randMax;
            FireResIV = 1.15 + randMax;
            IceResIV = 0.85 + randMax;
            HolyResIV = 0.85 + randMax;
            NatResIV = 1.15 + randMax;
            EvokeResIV = 1.15 + randMax;
            BloodResIV = 0.85 + randMax;
            EndResIV = 1.15 + randMax;
            LigResIV = 0.85 + randMax;
            EldResIV = 0.85 + randMax;
            AbyssResIV = 0.85 + randMax;
            TechResIV = 0.85 + randMax;
            BladeResIV = 1.15 + randMax;
            MindResIV = 1.15 + randMax;
            SoundResIV = 0.85 + randMax;
            WindResIV = 1.15 + randMax;
            SymResIV = 0.85 + randMax;
            SpiritResIV = 1.15 + randMax;
            DuneResIV = 1.15 + randMax;
            AquaResIV = 1.15 + randMax;
            ArmorPierceIV = 0 + randMax;
            ArmorShredIV = 0 + randMax;
            ProtPierceIV = 2 + randMax;
            ProtShredIV = 0.2 + randMax;
            CritDmgIV = 1.0 + randMax;
            CritIV = 0.05 + randMax;
        }
    }
 */
}